const Constantes = {
    TITULO: 'título',
    DESCRIPCION: 'descripción',
    TIPO_EPI: 'Tipo de equipo de protección individual',
    CANTIDAD_EPI: 'Cantidad de equipo de protección individual',
    LOTE_EPI: 'Lote de equipo de protección individual',
    FECHA_DISPONIBILIDAD: 'Fecha de disponibilidad',
    APELLIDO1: 'Primer apellido',
    APELLIDO2: 'Segundo apellido',
    NIF: 'Nif',
    ROLE: 'Role',
    EMAIL: 'Correo electrónico',
    PASSWORD: 'Contraseña',
    NOMBRE: 'Nombre',
    DIRECCION: 'Dirección',
    CAMPO_OBLIGATORIO: 'Falta alguno de los datos obligatorios para cambiar la contraseña',
    RESULTADO_TEST: 'Resultado',
    CLINICA_TEST: 'Clínica',
    FECHA_TEST: 'Fecha del test',
    TIPO_TEST: 'Tipo de test',
    PAUTA_COMPLETA_VACUNA: 'Pauta completa',
    FECHA_VACUNA: 'Fecha de la vacuna',
    TIPO_VACUNA: 'Tipo de la vacuna',
    HORA_INICIO: 'Hora de inicio',
    HORA_FIN: 'Hora de fin',
    HORAS_SEMANALES: 'Horas semanales',
    STOCK_MINIMO: 'Stock mínimo',
    MOTIVO_BAJA: 'Motivo',
}

module.exports = Constantes;